trigger:
  branches:
    include:
      - main

pool:
  name: 'LinuxPool'

steps:
# 1. Fetch secret from Key Vault
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure-Testing-Connection'   # must match your service connection name
    KeyVaultName: 'kv-testing-vm'
    SecretsFilter: 'vm-admin-password'
    RunAsPreJob: true

# 2. Install Terraform manually
- script: |
    curl -LO https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    sudo unzip terraform_1.5.7_linux_amd64.zip -d /usr/local/bin
    terraform version
  displayName: 'Install Terraform'

# 3. Run Terraform Init, Plan, Apply
- script: |
    cd infra
    terraform init
    terraform plan -var admin_username=azureuser -var admin_password=$(vm-admin-password)
    terraform apply -auto-approve -var admin_username=azureuser -var admin_password=$(vm-admin-password)
  displayName: 'Run Terraform'
